### ISSUE TITLE
__main__.py is broken

### ISSUE THREAD

**Issue by walkerh** [conda/cookiecutter-conda-python#9]
`__main__.py` imports the module `{{cookiecutter.package_name}}.cli` and then attempts to call the module rather than the function inside.

The name "cli" is both the name of a module and the name of a function inside that model.

Instead `__main__.py` should do this:

    from temp.cli import cli

    cli()

Here is a transcript of the problem and a hotfix:

    dev$ cookiecutter cookiecutter-conda-python
    full_name [Walker Hale]: 
    email [walker.hale.iv@gmail.com]: 
    github_username [walkerh]: 
    repo_name [repository_name]: temp
    package_name [temp]: 
    project_short_description [Short description]: 
    version [0.1.1-a0]: 
    dev$ cd temp
    temp$ python -m temp
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/hale/Documents/HGSC/dev/repo/third-party/temp/temp/__main__.py", line 3, in <module>
        cli()
    TypeError: 'module' object is not callable
    temp$ 
    temp$ # And now a hotfix...
    temp$ 
    temp$ cat <<EOD > temp/__main__.py
    > from temp.cli import cli
    > 
    > cli()
    > EOD
    temp$ 
    temp$ # Test it.
    temp$ python -m temp
    CLI template
    temp$

**Comment by walkerh** [comment]
Looks like this was fixed in ce1d3cd762d93edd20c331b9acfbe2629e1fc9f8. See [`__main__.py`](../blob/ce1d3cd762d93edd20c331b9acfbe2629e1fc9f8/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/__main__.py) in that commit.
